# Generated by Django 6.0.7 on 2026-07-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('store', 'line')},
        ),
    ]
