from rest_framework import routers
from store.views import StoreViewSet, AddressViewSet, ItemViewSet

router = routers.SimpleRouter() # creates a simple default router that generates URLS for a DRF ViewSet

router.register(r'Store', StoreViewSet, basename="store")
router.register(r'Address', AddressViewSet, basename="Address")
router.register(r'Item', ItemViewSet, basename="Item")


urlpatterns = router.urls # sets url pattersn for this app to those generated by the router for each view set